window:
  decorations: none
  startup_mode: Maximized
  dynamic_title: true
draw_bold_text_with_bright_colors: true
font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic

  size: 18.0
